server:
  port: 8084

spring:
  application:
    name: external-service
  datasource:
    url: jdbc:mysql://localhost:3306/bookkoo
    driver-class-name: org.mysql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

openapi:
  service:
    title: external-service doc
    version: 1.0.0
springdoc:
  api-docs:
    path: /external-service/v3/api-docs
  swagger-ui:
    path: /external-service/swagger-ui.html


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info
  metrics:
    tags:
      application: external-service

logging:
  level:
    org.springframework.web: "info"
    org.hibernate: "info"
  file:
    name: app/logs/application.log