server:
  port: 8083

spring:
  application:
    name: external-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mariadb://localhost:3309/uhbooba}
    username: ${SPRING_DATASOURCE_USERNAME:uhbooba}
    password: ${SPRING_DATASOURCE_PASSWORD:42seoul}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true

openapi:
  service:
    title: external-service doc
    version: 1.0.0
springdoc:
  api-docs:
    path: /external-service/v3/api-docs
  swagger-ui:
    path: /external-service/swagger-ui.html


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    org.springframework.web: "info"
    org.hibernate: "info"
  file:
    name: app/logs/application.log