server:
  port: 8080
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

spring:
  jwt:
    secret: 1kDPS1KxEX~BF2SAv66A=m!!B|Anx9{^$5x9oyO7]=MG&I.|CI:Xj|ZA(51KGOXY
  application:
    name: api-gateway
  #  security:
  #    user:
  #      name: user
  #      password: 1234
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          "[/**]":
            allowedOrigins:
              - "http://localhost:3000"
              - "http://localhost:80"
              - "http://localhost:8080"
              - "https://localhost:80"
              - "http://localhost:5173"
              - "https://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            exposedHeaders:
              - "Content-Disposition"
            allowCredentials: true

      routes:
        #        - id: user-service
        #          uri: lb://user-service
        #          predicates:
        #            - Path=/user-service/**,/users/**

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/env/**
          filters:
            - AuthorizationHeaderFilter
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/**,/users/**
          filters:
            #            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}

        - id: finance-service
          uri: lb://finance-service
          predicates:
            - Path=/finances/**,/fin-api/**
          filters:
            - AuthorizationHeaderFilter

        - id: finance-service
          uri: lb://finance-service
          predicates:
            - Path=/finance-service/**
          filters:
            - RewritePath=/finance-service/(?<segment>.*), /$\{segment}

        - id: external-service
          uri: lb://external-service
          predicates:
            - Path=/external-service/**,/externals/**

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /docs
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
      - url: /user-service/v3/api-docs
        name: 사용자 서비스
      - url: /finance-service/v3/api-docs
        name: 금융 서비스
      - url: /external-service/v3/api-docs
        name: 외부 서비스

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
