server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  jwt:
    secret: ${JWT_SECRET}
  coolsms:
    apikey: ${SMS_API_KEY}
    secret: ${SMS_API_SECRET}
    from: ${SMS_FROM_NUMBER}
  message:
    kafka:
      host: ${KAFKA_HOST}
      port: ${KAFKA_PORT}
      group-id: ${KAFKA_GROUP_ID}

openapi:
  service:
    title: user-service doc
    version: 1.0.0
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /docs


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    org.springframework.web: "info"
    org.hibernate: "info"
    org.apache.kafka: WARN
    org.springframework.kafka: WARN
  file:
    name: /logs/user-service/application.log
