server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mariadb://localhost:3307/uhbooba}
    username: ${SPRING_DATASOURCE_USERNAME:uhbooba}
    password: ${SPRING_DATASOURCE_PASSWORD:42seoul}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true

openapi:
  service:
    title: user-service doc
    version: 1.0.0
springdoc:
  api-docs:
    path: /user-service/v3/api-docs
  swagger-ui:
    path: /user-service/swagger-ui.html


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

#management:
#  endpoints:
#    web:
#      exposure:
#        include: prometheus, health, info
#  metrics:
#    tags:
#      application: user-service

logging:
  level:
    org.springframework.web: "info"
    org.hibernate: "info"
  file:
    name: app/logs/application.log